# <div class="alert alert-block alert-success">

<h1 align=center><font size = 5>CSE 350 </font></h1>
<h1 align=center><font size = 5> Lab 2 - hands-on notebook - Introduction to Numpy Array</font></h1>
    
    
# Dataset used is avaialble at https://archive.ics.uci.edu/ml/datasets/Wine+Quality
# </div>

### You can use this jupyter notebook to get to know the basis of numpy array, importing dataset from csv file and saving it as numpy array, and using such data to test your machine learning algorithms.

# Retrieving csv data represented as lists of Lists and converting to Numpy array

using Python and the csv package:
* Import the <FONT COLOR="RED">csv</FONT> library
* Open the <FONT COLOR="RED">winequality-red.csv</FONT> file
* * With the file open, create a new <FONT COLOR="RED">csv.reader</FONT> object
* * * Pass in the keyword argument delimiter=";" to make sure that the records are split up on the semicolon character instead of the default comma character
* * Call the <FONT COLOR="RED">list</FONT> type to get all the rows from the file
* * Assign the result to <FONT COLOR="RED">wines</FONT>


In [56]:
import csv
with open('../input/winequality-red.csv', 'r') as f:
    wines = list(csv.reader(f, delimiter=';'))
    
# ## with statement could be implemented like 
# try:
#    f = open('../input/winequality-red.csv', 'r')
# finally:
#    f.close()

In [57]:
wines

[['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'],
 ['7.4',
  '0.7',
  '0',
  '1.9',
  '0.076',
  '11',
  '34',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  '5'],
 ['7.8',
  '0.88',
  '0',
  '2.6',
  '0.098',
  '25',
  '67',
  '0.9968',
  '3.2',
  '0.68',
  '9.8',
  '5'],
 ['7.8',
  '0.76',
  '0.04',
  '2.3',
  '0.092',
  '15',
  '54',
  '0.997',
  '3.26',
  '0.65',
  '9.8',
  '5'],
 ['11.2',
  '0.28',
  '0.56',
  '1.9',
  '0.075',
  '17',
  '60',
  '0.998',
  '3.16',
  '0.58',
  '9.8',
  '6'],
 ['7.4',
  '0.7',
  '0',
  '1.9',
  '0.076',
  '11',
  '34',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  '5'],
 ['7.4',
  '0.66',
  '0',
  '1.8',
  '0.075',
  '13',
  '40',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  '5'],
 ['7.9',
  '0.6',
  '0.06',
  '1.6',
  '0.069',
  '15',
  '59',
  '0.9964',
  '3.3',
  '0.46',
  '9.4',
  '5'],
 ['7.3',
  '0

A <FONT COLOR="RED">**2-dimensional array**</FONT> is also known as a <FONT COLOR="RED">**matrix**</FONT>, and is something you should be familiar with. In fact, it’s just a different way of thinking about a list of lists. A matrix has rows and columns. By specifying a row number and a column number, we’re able to extract an element from a matrix.

In a NumPy array, the number of dimensions is called the <FONT COLOR="RED">**rank**</FONT>, and each dimension is called an <FONT COLOR="RED">**axis**</FONT>. So the rows are the first axis, and the columns are the second axis.

* Import the numpy package.
* Pass the list of lists wines into the array function, which converts it into a NumPy array.
* * Exclude the header row with list slicing.
* * Specify the keyword argument dtype to make sure each element is converted to a float. We’ll dive more into what the dtype is later on.

In [58]:
import numpy as np
wines = np.array(wines[1:], dtype=float)

In [59]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

We can check the number of rows and columns in our data using the <FONT COLOR="RED">**shape**</FONT> property of NumPy arrays:

In [60]:
wines.shape

(1599, 12)

# Alternative: Using NumPy to Read In Files

It’s possible to use NumPy to directly read csv or other files into arrays. We can do this using the <FONT COLOR="RED">numpy.genfromtxt</FONT> function. We can use it to read in our initial data on red wines.

* Use the <FONT COLOR="RED">genfromtxt</FONT> function to read in the <FONT COLOR="RED">winequality-red.csv</FONT> file.
* Specify the keyword argument <FONT COLOR="RED">delimiter=";"</FONT> so that the fields are parsed properly.
* Specify the keyword argument <FONT COLOR="RED">skip_header=1</FONT> so that the header row is skipped.

In [61]:
wines = np.genfromtxt("../input/winequality-red.csv", delimiter=";", skip_header=1)

In [62]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

# Indexing NumPy Arrays

We can use array indexing to select individual elements, groups of elements, or entire rows and columns. One important thing to keep in mind is that just like Python lists, <FONT COLOR="RED">NumPy is zero-indexed</FONT>, meaning that the index of the first row is 0, and the index of the first column is 0. If we want to work with the fourth row, we’d use index 3, if we want to work with the second row, we’d use index 1, and so on. We’ll again work with the wines array:

In [64]:
wines[0,0]

7.4

Since we’re working with a 2-dimensional array in NumPy, we specify 2 indexes to retrieve an element. **The first index is the row**, or axis 1, index, and **the second index is the column**, or axis 2, index. Any element in wines can be retrieved using 2 indexes.

In [ ]:
wines[2,3]

**Slicing** also works.

We can select an **entire column** by specifying that we want all the elements, from the first to the last. We specify this by just using the colon (:), with no starting or ending indices. The below code will select the entire fourth column:

In [68]:
wines[1:4,3]

array([2.6, 2.3, 1.9])

We selected an entire column above, but we can also extract an **entire row**:

In [66]:
wines[3,:]

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

If we take our indexing to the extreme, we can select the entire array using two colons to select all the rows and columns in wines. This is a great party trick, but doesn’t have a lot of good applications:

In [67]:
wines[:,:]

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

# Assigning Values To NumPy Arrays

We can also use indexing to assign values to certain elements in arrays. We can do this by assigning directly to the indexed value:

In [69]:
wines[1,5] = 10

We can do the same for slices. To overwrite an entire column, we can do this:

In [70]:
wines[:,10] = 50

The above code overwrites all the values in the eleventh column with 50.

In [71]:
wines[:,:] = 30

# NumPy Data Types

As we mentioned earlier, each NumPy array can store elements of a single data type. For example, <FONT COLOR="red">wines</FONT> contains only float values. **NumPy stores values using its own data types, which are distinct from Python types like <FONT COLOR="red">float</FONT> and <FONT COLOR="red">str</FONT>.** This is because the core of NumPy is written in a programming language called C, which stores data differently than the Python data types. NumPy data types map between Python and C, allowing us to use NumPy arrays without any conversion hitches.

You can find the data type of a NumPy array by accessing the dtype property:

In [72]:
wines.dtype

dtype('float64')

NumPy has several different data types, which mostly map to Python data types, like <FONT COLOR="red">float</FONT>, and <FONT COLOR="red">str</FONT>. You can find a full listing of NumPy data types, but here are a few important ones:

* <FONT COLOR="red">float</FONT> — numeric floating point data.
* <FONT COLOR="red">int</FONT> — integer data.
* <FONT COLOR="red">string</FONT> — character data.
* <FONT COLOR="red">object</FONT> — Python objects.

Data types additionally end with a suffix that indicates how many bits of memory they take up. So <FONT COLOR="red">int32</FONT> is a 32 bit integer data type, and <FONT COLOR="red">float64</FONT> is a 64 bit float data type.

In [73]:
wines_int = wines.astype(int)

wines_int

array([[30, 30, 30, ..., 30, 30, 30],
       [30, 30, 30, ..., 30, 30, 30],
       [30, 30, 30, ..., 30, 30, 30],
       ...,
       [30, 30, 30, ..., 30, 30, 30],
       [30, 30, 30, ..., 30, 30, 30],
       [30, 30, 30, ..., 30, 30, 30]])

# NumPy Array Operations

# # Single Array Math

In [ ]:
wines[:,11]

In [74]:
wines[:,11] += 10

wines[:,11]

array([40., 40., 40., ..., 40., 40., 40.])

In [75]:
wines[:,11] *= 2

wines[:,11]

array([80., 80., 80., ..., 80., 80., 80.])

# # Multiple Array Math

In [76]:
wines[:,11] + wines[:,11]

array([160., 160., 160., ..., 160., 160., 160.])

# NumPy Array Methods

In [77]:
wines[:,11].sum()

127920.0

If we call sum across the wines matrix, and pass in **axis=0**, we’ll find the sums over the first axis of the array. This will give us the sum of all the values in every column. This may seem backwards that the sums over the first axis would give us the sum of each column, but one way to think about this is that the specified axis is the one “going away”. So if we specify axis=0, we want the rows to go away, and we want to find the sums for each of the remaining axes across each row:

In [78]:
wines.sum(axis=0)

array([ 47970.,  47970.,  47970.,  47970.,  47970.,  47970.,  47970.,
        47970.,  47970.,  47970.,  47970., 127920.])

We can verify that we did the sum correctly by checking the shape. The shape should be 12, corresponding to the number of columns:

In [79]:
wines.sum(axis=0).shape

(12,)

If we pass in **axis=1**, we’ll find the sums over the second axis of the array. This will give us the sum of each row:

In [80]:
wines.sum(axis=1)

array([410., 410., 410., ..., 410., 410., 410.])

If we pass in axis=1, we’ll find the sums over the second axis of the array. This will give us the sum of each row:There are several other methods that behave like the sum method, including:

* numpy.ndarray.**mean** — finds the mean of an array.
* numpy.ndarray.**std** — finds the standard deviation of an array.
* numpy.ndarray.**min** — finds the minimum value in an array.
* numpy.ndarray.**max** — finds the maximum value in an array.

### Now, you can test the machine learning algorithms with provided sample jupyter notebook.